<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper form-horizontal">
            <div class="content solo-page">
                <h3 class="title-editor border-blue text-center">
                    <?php echo  p__("catalogpro", "Categories"); ?>
                </h3>

                <div class="subcontent content-color container-fluid">
                    <div class="form-group">
                        <div class="col-md-12">
                            <a href="/catalogpro/category/add" id="add_category"
                                class="color-blue btn sb-tour pull-right">
                                <?php echo  p__("catalogpro", "Create a new Category"); ?>
                            </a>
                            <table id="dynamic-category" class="table content-white-bkg sb-pager">
                                <thead>
                                    <tr class="border-grey">
                                        <th style="width: 5%"></th>
                                        <th style="width: 20%;"><?php echo  p__("catalogpro", "Image"); ?></th>
                                        <th data-dynatable-column="category_name" style="width: 20%;">
                                            <?php echo  p__("catalogpro", "Category Name"); ?></th>
                                        <th style="width: 30%;"><?php echo  p__("catalogpro", "Short Description"); ?>
                                        </th>
                                        <th data-dynatable-column="is_active" style="width: 10%;">
                                            <?php echo  p__("catalogpro", "Status"); ?></th>
                                        <th style="width: 10%"><?php echo  p__("catalogpro", "QRcode"); ?></th>
                                        <th style="width: 5%"></th>
                                        <th style="width: 5%"></th>
                                    </tr>
                                </thead>
                                <tbody class="connectedSortable"></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.css" media="screen" rel="stylesheet"
    type="text/css">
<script type="text/javascript" src="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.js"></script>

<style type="text/css">
#dynamic-category {
    margin-top: 15px;
}
</style>

<script type="text/javascript">
var uriParams = {};
let rowTemplate = `
    <tr class="dynarow" id="element_(ID)">
        <td><i class="fa fa-arrows" aria-hidden="true"></i></td>
        <td><img src="/images/application/(IMAGE)" width="40px" height="40px"></td>
        <td>(NAME)</td>
        <td>(DESCRIPTION)</td>
        <td>(STATUS)</td>
        <td><a target="_blank" btn btn-xs btn-default" href="/catalogpro/category/qrcode/value_id/(VALUEID)/category_id/(ID)">
             <i class="fa fa-qrcode" aria-hidden="true"></i>
          </a></td>
        <td>
        <a class="edit-category btn btn-xs btn-info" href="/catalogpro/category/edit/id/(ID)">
             <?php echo P__("catalogpro", "Edit") ?>
          </a>
        </td>
        <td> 
          <a class="delete-category btn btn-xs btn-danger" href="/catalogpro/category/delete/id/(ID)">
             <?php echo P__("catalogpro", "Delete") ?>
          </a>
        </td>
       
    </tr>`;

function rowWriter(rowIndex, record, columns, cellWriter) {
    return rowTemplate
        .replace(/\(ID\)/g, record.id)
        .replace(/\(IMAGE\)/g, record.image)
        .replace(/\(NAME\)/g, record.category_name)
        .replace(/\(VALUEID\)/g, record.value_id)
        .replace(/\(DESCRIPTION\)/g, record.short_description)
        .replace(/\(STATUS\)/g, record.status);
}
$.dynatableSetup({
    table: {
        defaultColumnIdStyle: 'noStyle'
    },
    features: {
        paginate: true,
        sort: true,
        pushState: true,
        search: true,
        recordCount: true,
        perPageSelect: false,
    },
});

let tableCustomers = $('#dynamic-category');

tableCustomers.bind('dynatable:preinit', function(e, dynatable) {
    dynatable.utility.textTransform.noStyle = function(text) {
        return text;
    };
});

tableCustomers.bind('dynatable:afterProcess', function(e, data) {
    uriParams = data.queries;
});

tableCustomers.bind('dynatable:push', function(e, dynatable) {
    uriParams = dynatable.queries;
});

// And on the table
tableCustomers.dynatable({
    dataset: {
        ajax: true,
        ajaxUrl: '/catalogpro/category/find-all',
        ajaxOnLoad: true,
        records: [],
        perPageDefault: 25
    },
    inputs: {
        processingText: '<?php echo P__("catalogpro", "Loading ...") ?>',
        searchPlaceholder: '<?php echo P__("catalogpro", "Search Category ...") ?>',
        recordCountText: '<?php echo P__("catalogpro", "Showing") ?> ',
        filteredFrom: ' (<?php echo P__("catalogpro", "filtered from #TOTAL# total records") ?>)',
        recordText: '<?php echo P__("catalogpro", "record") ?>',
        recordTextPlural: '<?php echo P__("catalogpro", "records") ?>',
        textOf: '<?php echo P__("catalogpro", "of") ?>',
        textTo: '<?php echo P__("catalogpro", "to") ?>',
        queries: $('.dt-search')
    },
    writers: {
        _rowWriter: rowWriter
    }
});

$(document).off("click", ".delete-category");
$(document).on("click", ".delete-category", function(e) {
    e.preventDefault();
    let deleteHref = $(this).attr("href");
    swal({
        title: '<?php echo P__("catalogpro", "Confirmation") ?>',
        text: '<?php echo P__("catalogpro", "Are you sure you want to delete this Category?") ?>',
        showCancelButton: true,
        confirmButtonColor: '#0099C7',
        confirmButtonText: '<?php echo P__("catalogpro", "Yes, delete!")?>',
        cancelButtonText: '<?php echo P__("catalogpro", "No, go back") ?>',
        buttons: true
    }, function(value) {
        if (!value) {
            return false;
        }

        formget(deleteHref, {},
            function(data) {
                feature_form_success(data.message);
                // Reload only on success and when done!
                setTimeout(function() {
                    location.reload();
                }, 1500)
            },
            function(data) {
                feature_form_error(JSON.parse(data.responseText).message);
            },
            false);
    });
});

var $tabs = $('#dynamic-category');
$(document).ready(function() {
    $("tbody.connectedSortable")
        .sortable({
            connectWith: ".connectedSortable",
            appendTo: $tabs,
            helper: "clone",
            cursor: 'move',
            zIndex: 999990,
            stop: function(event, ui) {
                var data = $(this).sortable('toArray');

                $.ajax({
                    method: "POST",
                    url: "<?php echo $this->getUrl('catalogpro/category/sortable'); ?>",
                    data: {
                        data: data,
                        parent_id: 0
                    }
                }).done(function(msg) {});
            }
        })
        .disableSelection();
});
</script>

<style type="text/css">
.dynatable-record-count {
    bottom: 0px !important;
}

.text-blue {
    color: #0099c7;
}
</style>